# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\"g\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\r\n\x05start\x18\x03 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x02\x12\x13\n\x0bpartitioned\x18\x05 \x01(\x08\x12\x0c\n\x04time\x18\x06 \x01(\x01\"0\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\xdb\x01\n\rStatusRequest\x12\x13\n\x0bworker_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x12\n\nbegin_time\x18\x04 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x01\x12?\n\x0cruntime_info\x18\x06 \x03(\x0b\x32).scheduler.StatusRequest.RuntimeInfoEntry\x1a\x32\n\x10RuntimeInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x97\x01\n\x10SchedulerService\x12>\n\x0bProcessTask\x12\x16.scheduler.TaskRequest\x1a\x17.scheduler.TaskResponse\x12\x43\n\x0cReportStatus\x12\x18.scheduler.StatusRequest\x1a\x19.scheduler.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST_RUNTIMEINFOENTRY']._loaded_options = None
  _globals['_STATUSREQUEST_RUNTIMEINFOENTRY']._serialized_options = b'8\001'
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=133
  _globals['_TASKRESPONSE']._serialized_start=135
  _globals['_TASKRESPONSE']._serialized_end=183
  _globals['_STATUSREQUEST']._serialized_start=186
  _globals['_STATUSREQUEST']._serialized_end=405
  _globals['_STATUSREQUEST_RUNTIMEINFOENTRY']._serialized_start=355
  _globals['_STATUSREQUEST_RUNTIMEINFOENTRY']._serialized_end=405
  _globals['_STATUSRESPONSE']._serialized_start=407
  _globals['_STATUSRESPONSE']._serialized_end=440
  _globals['_SCHEDULERSERVICE']._serialized_start=443
  _globals['_SCHEDULERSERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
