FROM python:3.9-alpine

WORKDIR /app
COPY . .

# Install bash, python3, pip, docker client, and Docker-in-Docker (DinD) support
RUN apk add --no-cache bash python3 py3-pip docker-cli docker

# Set up and activate a virtual environment
RUN python3 -m venv /venv
RUN . /venv/bin/activate

# Install necessary Python packages inside the virtual environment
RUN /venv/bin/pip install --no-cache-dir grpcio grpcio-tools

EXPOSE 50051

# Command to start Docker daemon and run your Python worker
CMD ["sh", "-c", "dockerd & /venv/bin/python worker.py"]
