apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3  # Number of worker instances
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: willma17/worker-service:latest  # Your Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: SCHEDULER_ADDRESS
              value: "192.168.1.100:50052"  # Make sure this is reachable
          securityContext:
            privileged: true  # Allows running Docker inside the worker pod
          volumeMounts:
            - mountPath: /var/run/docker.sock  # Allows the worker to use Docker
              name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
